name: Deploy to Grebedoc

on:
  push:
    branches: ["main"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6

      - name: Create tarball
        env:
          ZSTD_CLEVEL: "3"
        run: "tar --zstd --create --directory src --file deploy.tar.zst ."

      - name: Deploy artifact
        run: |
          curl http://ril100.techtoto.dev/ \
            -X PUT \
            -H 'Authorization: Pages ${{ secrets.GREBEDOC_TOKEN }}' \
            -H 'Content-Type: application/x-tar+zstd' \
            --data-binary @deploy.tar.zst
